### ISSUE TITLE
Compiler server friendliness

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.vdom#1]
With compiler server it gives the following error every other build:

```
--macro:1: character 0 : Type name vdom.macros.Loader is redefined from module vdom.macros.Loader
```

**Comment by kevinresol** [comment]
oops, seems like a js-virtual-dom problem

**Comment by back2dos** [comment]
Yeah, this one is particularly crazy, because `vdom.macros.Loader` is really just a plain class with a macro in it, that [is called explicitly](https://github.com/back2dos/js-virtual-dom/blob/ec86801393a00633a707c7209b0a152f6f6d681d/src/vdom/VDom.hx#L14).
 
I have seen other hickups, most notably tink_lang stopping to work and the renderer being lost.

**Comment by back2dos** [comment]
I guess this is no longer relevant with gen4.
